#ifndef PICO_REST_SENSOR_HAL_TASK_PRIORITIES_H_
#define PICO_REST_SENSOR_HAL_TASK_PRIORITIES_H_

#define MAIN_TASK_PRIORITY (tskIDLE_PRIORITY + 10UL)
#define BUTTON_PRESS_TASK_PRIORITY (tskIDLE_PRIORITY + 10UL)
#define STATUS_TASK_PRIORITY (tskIDLE_PRIORITY + 1UL)

#endif  // PICO_REST_SENSOR_HAL_TASK_PRIORITIES_H_
