#ifndef __HAL__TASK_PRIORITIES__
#define __HAL__TASK_PRIORITIES__

#define MAIN_TASK_PRIORITY (tskIDLE_PRIORITY + 10UL)
#define STATUS_TASK_PRIORITY (tskIDLE_PRIORITY + 1UL)
#define LOGGER_TASK_PRIORITY (tskIDLE_PRIORITY + 2UL)
#define REST_API_TASK_PRIORITY (tskIDLE_PRIORITY + 5UL)
#define BUTTON_PRESS_TASK_PRIORITY (tskIDLE_PRIORITY + 3UL)

#endif
