# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ndreasndersson/picow-plant-moisture-sensor:latest
      volumes:
        - ${{ github.workspace }}:/project

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build
      run: ./build_and_combine.sh ${{env.BUILD_TYPE}}

    - name: Static code analysis
      run: ./run_codechecker_and_create_report.sh

    - name: Deploy
      uses: actions/upload-artifact@v4
      with:
        name: Release
        path: |
          build/*.uf2
          build/*.bin
          build/**/PICO_BOOTLOADER.bin
          ${{ steps.codechecker.outputs.result-html-dir }}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
